{% set version = "0.9" %}

package:
  name: mppp
  version: {{ version }}

source:
  url: https://github.com/bluescarni/mppp/archive/v{{ version }}.tar.gz
  sha256: b31a48395a5fb9931868a8cb783222b87a4b2437affea287a23a6fcb706a18c6

build:
  number: 0
  skip: true  # [win and py<35]
  features:
    - vc14  # [win and py>=35]

requirements:
  build:
    - python              # [win]
    - vc 14               # [win and py>=35]
    - toolchain
    - cmake
    - gmp 6.1.*           # [unix]
    - mpir                # [win]
    - mpfr 3.1.*
  run:
    - vc 14               # [win and py>=35]
    - gmp 6.1.*           # [unix]
    - mpir                # [win]
    - mpfr 3.1.*
    - libgfortran         # [linux]


test:
  commands:
    - test -f $PREFIX/include/mp++/mp++.hpp               # [unix]
    - if not exist %LIBRARY_INC%\\mp++\\mp++.hpp exit 1   # [win]

about:
  home: https://bluescarni.github.io/mppp/
  license: MPL2
  license_file: COPYING
  summary: 'A modern C++ library for multiprecision arithmetic'

extra:
  recipe-maintainers:
    - bluescarni
