{% set version = "0.5" %}

package:
  name: mppp
  version: {{ version }}

source:
  url: https://github.com/bluescarni/mppp/archive/v{{ version }}.tar.gz
  sha256: f9c0371724f3f336d2f1373c25d0307c55cd5b3a598582190c250f789c1d286f

build:
  number: 0
  skip: true  # [win and py<35]
  features:
    - vc14  # [win and py>=35]

requirements:
  build:
    - python              # [win]
    - vc 14               # [win and py>=35]
    - toolchain
    - cmake
    - gmp 6.1.*           # [unix]
    - mpir                # [win]
    - mpfr 3.1.*
  run:
    - vc 14               # [win and py>=35]
    - gmp 6.1.*           # [unix]
    - mpir                # [win]
    - mpfr 3.1.*


test:
  commands:
    - test -f $PREFIX/include/mp++/mp++.hpp               # [unix]
    - if not exist %LIBRARY_INC%\\mp++\\mp++.hpp exit 1   # [win]

about:
  home: https://bluescarni.github.io/mppp/
  license: MPL2
  license_file: COPYING
  summary: 'A C++11 header-only library for multiprecision arithmetic'

extra:
  recipe-maintainers:
    - bluescarni
