{% set version = "0.4" %}

package:
  name: mppp
  version: {{ version }}

source:
  url: https://github.com/bluescarni/mppp/archive/v{{ version }}.tar.gz
  sha256: 0c9c7049a0041c167c2f11f7e8eb029636852bdaaf4e4a9dbead5b46ff4e6480

build:
  number: 0
  skip: true  # [win and py<35]
  features:
    - vc14  # [win and py>=35]

requirements:
  build:
    - python              # [win]
    - vc 14               # [win and py>=35]
    - toolchain
    - cmake
    - gmp                 # [unix]
    - mpir                # [win]
    - mpfr 3.1.*
  run:
    - vc 14               # [win and py>=35]
    - gmp                 # [unix]
    - mpir                # [win]
    - mpfr 3.1.*


test:
  commands:
    - test -f $PREFIX/include/mp++/mp++.hpp               # [unix]
    - if not exist %LIBRARY_INC%\\mp++\\mp++.hpp exit 1   # [win]

about:
  home: https://bluescarni.github.io/mppp/
  license: MPL2
  license_file: COPYING
  summary: 'A C++11 header-only library for multiprecision arithmetic'

extra:
  recipe-maintainers:
    - bluescarni
