travis:
  secure:
    BINSTAR_TOKEN: M0d3oJ2wT3lbwW60i6UV/Fpmzl40FlIu7rjtU/h4SBa7sjRrW+BMaT0T8Phh5l7uTTu0HZhTzvGdGxpC84dYAR80BFXIgqnk/xlvSwzTmC6SQk+4wC9Fd3DMXVpXKkT8bqGNXOKOxTwtroSZihpAt0Q1sUv3M+hYtI7iCTJYO9ipk3ZlB/UfG8n+g+OJwyCCAfbwETFC7I06L92lCoOqtNAl1MpU0Y6R1d0NYbS1435XGzb1hQYTCXy2mB6pRQt8E2DVBtiw5vVhMq+cgSsb6UYFBMn7pVfR3MAvF1A2exl6fHx0YXRE3so83GW4BGebRXeqi1+pxZnFd4548KWpcdoKtIvaGewU2D7hUfVNMwQZR4pGPJqxDOU7/U6dsD4UTOinJEmlWk8CT4+qT3PJKlBeTjLmqd3UL+a3kRk4K3Kfizl9wO/s5umwaRwJJSJTraqWs2c+DC9ebRzn5TbT84g6LuP4WUcWfarBPA3JOq9gOWyf0lihSaUFj7xYq7RbMRNnF3C7MryCVC4ykUNYpxpAjhd8UY7OL5M2BIFPNXPVW8uwzx01pqO9davci424F5AmZgt4iLqNtpKp35OASkMJHvetp3SO9ss5zF7Lav00unXYSrgl1XHPPXKZtLcdF/iVOCp4pu/byTG2HBJB065cDA6mkp6MarFivP7FEyk=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
